zksecurity/noname

src/imports.rs
src/name_resolution/expr.rs
src/parser/types.rs
src/stdlib/crypto.rs
src/stdlib/mod.rs
src/type_checker/mod.rs

The static and const builtins doesn't work for generic types. These changes are for adapting to different backends.

refactor: builtins

---

examples/const.asm
examples/iterate.asm
examples/public_output.asm
src/backends/kimchi/mod.rs
src/backends/kimchi/prover.rs
src/circuit_writer/mod.rs

https://github.com/zksecurity/noname/issues/58
The kimchi prover/ verifier already cover the public output constraints. Here we add a test to ensure this is the case.

Add test to check incorrect output for kimchi backend

---

Cargo.lock
Cargo.toml
src/backends/kimchi/mod.rs
src/backends/mod.rs
src/backends/r1cs/builtin.rs
src/backends/r1cs/mod.rs
src/backends/r1cs/snarkjs.rs
src/bin/noname.rs
src/cli/cmd_build_and_check.rs
src/cli/mod.rs
src/inputs.rs
src/tests/examples.rs
src/witness.rs

Here are the commands to verify the whole process.
```bash
cargo run new -p test
cargo run run --backend r1cs --path test --private-inputs '{"yy": "1"}' --public-inputs '{"xx": "2"}'
snarkjs wchk test/output.r1cs test/output.wtns
snarkjs powersoftau new bls12-381 12 pot12_0000.ptau -v
snarkjs powersoftau contribute pot12_0000.ptau pot12_0001.ptau --name="First contribution" -v
snarkjs powersoftau prepare phase2 pot12_0001.ptau pot12_final.ptau -v
snarkjs groth16 setup test/output.r1cs pot12_final.ptau test_0000.zkey
snarkjs zkey contribute test_0000.zkey test_0001.zkey --name="1st Contributor Name" -v
snarkjs zkey export verificationkey test_0001.zkey verification_key.json
snarkjs groth16 prove test_0001.zkey test/output.wtns proof.json public.json
snarkjs groth16 verify …
```

Support R1CS

---

.gitattributes

Add simple syntax highlighting based on Rust to prettify things. To see how it looks like, check [my fork](https://github.com/eightfilms/noname/tree/main/examples)

chore: add Rust syntax highlighting for .no files

---

Cargo.lock

Fixes the `stdsimd` feature issue that is causing gh-pages action to fail.
Done using `cargo update -p ahash`.
See: https://github.com/tkaitchuck/aHash/issues/200

chore(deps): bump ahash to `0.7.8`

---

.github/workflows/gh-pages.yml
.github/workflows/rust.yml

The actions-rs cargo repository has been [archived](https://github.com/actions-rs/cargo), so this PR just updates the CI to use [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) instead. It also has a more concise one-line usage with sane defaults.

chore(ci): update CI to use dtolnay/rust-toolchain

---

README.md
src/cli/cmd_build_and_check.rs

the default example didn't work with R1CS. Also I made R1CS the default so that we don't have to pass `--backend` by default.

r1cs is default backend, default example works

---

src/backends/r1cs/snarkjs.rs
src/cli/cmd_build_and_check.rs

Closes #102 
Related: #100, addresses comments on unused results
Originally, all `Result`s were ignored. This PR updates the two structs/impls in question to: use either the appropriate `io::Result` or the standard `std::result::Result` (which the circom dep returns)

chore: refactor `SnarkjsExporter` and `WitnessWriter` to handle errors

---

src/backends/kimchi/mod.rs
src/backends/r1cs/mod.rs

Closes #39 
- Makes `CellVar` index private
- Refactor `private_input_indices` to `private_input_cell_vars` as a vector of `CellVar`s instead of indices

chore: make CellVar index private

---

src/cli/cmd_build_and_check.rs

derive `ValueEnum` for `BackendOpt` - we use `clap`'s builtin enum support to do validation and parsing.
Also implement `From<BackendOpt> for BackendKind` to simplify the flow.
Some screenshots:
Not specifying any backends: `cargo run -- run --backend`
Mistyping a backend: `cargo run -- run --backend kimchi`

chore(cli): cleanup backend option

---

Cargo.lock
Cargo.toml
book/book.toml
src/parser/types.rs

Extracted from #100 
This follows the original implementation. 2 `Ident`s should be equal if their values are equal, even if their `Span`s are different. This also includes manually implementing `Hash` to allow for this.

feat(types): impl `PartialEq` and `Hash` for `Ident` instead of `ModulePath`

---

examples/iterate.no
src/error.rs
src/type_checker/checker.rs

Fix https://github.com/zksecurity/noname/issues/93
for the following example 
```
use std::crypto;
fn double(xxx: Field) -> Field {
return xxx + xxx;
} 
fn main(pub public_input: Field, private_input: Field) {
let double = private_input;
assert_eq(double, double(private_input));
}
``` 
the compiler should return
```
Error:   × Looks like something went wrong in type-checker
╭─[../../examples/example.no:2:1]
2 │ 
3 │ fn double(xxx: Field) -> Field {
·       ─┬─
·          ╰── here
4 │     return xxx + xxx;
╰────
help: function name `double` is already in use by a variable present in the scope
```
I updated  the test after reflecting the new checks work by making the pipeline fail at https://github.com/zksecurity/noname/actions/runs/9528372535/job/26265972691?pr=125#step:6:324

Function name in use check

---

Cargo.lock
Cargo.toml
src/backends/r1cs/arkworks.rs
src/backends/r1cs/mod.rs

This PR upstreams the [`ark-noname`](https://github.com/dmpierre/ark-noname) code,  but using arkworks `3.0`. Aims to close [135](https://github.com/zksecurity/noname/issues/135).

feat: support conversion to arkworks constraints

---

examples/generic_builtin_bits.no
src/name_resolution/expr.rs
src/parser/types.rs
src/stdlib/bits.rs
src/stdlib/builtins.rs
src/stdlib/crypto.rs
src/stdlib/mod.rs
src/type_checker/mod.rs

What I did in this PR:
* move bits and builtins stuff in their own rust modules
* introduce `Module` trait so that each module can just implement that
This is still a bit ugly (why enum lol) but it should be fine as it should be temporary. (because ideally modules should be declared as their own files, see https://github.com/zksecurity/noname/issues/157)
This will allow us to focus on implementing things instead of improving the modules. For example, if we want to mix native and builtins we can have builtins live in `std::bits_builtins` and the native code in `std::bits`.

proper modules

---

src/error.rs
src/type_checker/checker.rs

Improved the errors returned by the type checker: replaced most of the panics with errors which also display nicely the relevant code spans.
The code below sums up all the possible cases that now return nice errors
```rust
struct Thing {
xx: Field,
yy: Field,
}
fn main(pub xx: Field) {
let mut thing = Thing { xx: xx, yy: xx + 1 };
thing.xx = true;
// help: type 'Field' and 'Bool' are not compatible
let thing2 = true;
let thing_int = 3;
thing2.asd = false;
// help: field access can only be applied on custom structs
let thing3 = thing.zz;
// help: struct `Thing` does not have a field called `zz`
let thing4 = thing.not_existent();
// help: struct `Thing` does not have a method called `not_existent`
let yy = if 3 { thing2 } else { thing2 };
// help: if-else condition is expected to be a …
```

Improve type checker errors

---

.github/workflows/rust.yml
src/negative_tests.rs

Added test coverage checks on the constraint. Resolves issue #49. Continuing from PR #174 (Made a separate PR since it was easier to add the new tests from a new branch into branch `rfc-0-impl` instead of the old branch)

Added test coverage checks on the constraint

---

src/circuit_writer/writer.rs
src/mast/mod.rs
src/name_resolution/context.rs
src/parser/types.rs
src/type_checker/checker.rs

This PR aims at addressing issue #176 by refactoring the `ForLoop` and `IteratorLoop` structures into a single structure
```rust
ForLoop {
var: Ident,
argument: ForLoopArgument,
body: Vec<Stmt>,
}
```
using the `ForLoopArgument` enum as the argument type.
```rust
pub enum ForLoopArgument {
Range(Range),
Iterator(Box<Expr>),
}
```
Indeed this would have been much cleaner to implement iterators in this way from the beginning! I tried to merge as much as possible the code in the `ForLoop` and `IteratorLoop` cases throughout the compilation flow, but sometimes it ended up as a big `match` statement on the argument (e.g., in `circuit_writer.rs`).
Maybe in the future this could be refactored even further introducing a generic iterator trait in the codebase, having ranges and vectors as …

Refactor for loops and iterators in the same statement structure

---

src/backends/r1cs/mod.rs
src/stdlib/builtins.rs

This is a logging feature to help debugging.
Usage:
```rust
let sum = var1 + var2;
log(sum); 
```
It should print something like:
```
---log span: Span { filename_id: 1, start: 147, len: 7 }---
typ: Some(Field { constant: false })
mutable: false
cvar: v_2 + v_1
```
Because it is a builtin function, so it only accesses to the info at compilation time.
It is quite common to check the values behind these variables. So we could record the cell var index at the backend, and print out the relevant witness values when generating witnesses.

feat: log builtin

---

src/mast/ast.rs
src/mast/mod.rs
src/parser/types.rs

Changes: 
1. Since every functions need to be instantiated, the `ctx.generic_func_scope` is not necessary for determining whether it needs to generate new node id. Thus, `ctx.generic_func_scope` is removed to avoid unexpected behavior in terms of handling the node ids at mast phase.
2. A fix to avoid re-instantiate a same function.

Fix: avoid node overriding and re-instantiate a same function

---

src/mast/mod.rs
src/negative_tests.rs
src/stdlib/native/int.no
src/type_checker/checker.rs
src/type_checker/mod.rs

This is a fix to propagate the constant values from struct fields also.
This fix allows the struct fields to be passed as an constant argument for a generic function. eg:
```rust
struct Uint8 {
inner: Field,
bit_len: Field,
}
fn Uint8.new(val: Field) -> Uint8 {
let bit_len = 8;
// range check
let ignore_ = bits::to_bits(bit_len, val);
return Uint8 {
inner: val,
bit_len: bit_len
};
}
fn Uint8.less_than(self, rhs: Uint8) -> Bool {
// this won't work without this PR fix
return comparator::less_than(self.bit_len, self.inner, rhs.inner);
}
```

Fix: Allow struct fields to propagate constants

---

book/src/rfc/rfc-0-generic-parameters.md
src/negative_tests.rs
src/type_checker/checker.rs
src/type_checker/fn_env.rs

We should also forbid generic function calls with mutable variables that even out of the for loop scope. Otherwise, it will run into unrolling issue.
For example
```rust
fn gen(const LEN: Field) -> [Field; LEN] {
return [0; LEN];
}
fn loop() {
let mut size = 2;
for ii in 0..3 {
gen(size); // should be forbidden even the var is out of forloop scope
size = size + 1;
}
}
```
Even the `size` variable is not within the for loop scope, but it is mutable. 
Similarly, this issue can also happen to struct that is out of for loop scope, but mutable.

fix: forbid generic call with mutable vars

---

src/backends/kimchi/mod.rs
src/backends/mod.rs
src/backends/r1cs/mod.rs
src/stdlib/builtins.rs

Previously, the log function is to print out the compilation info, such as the type of a variable.
This update is to make it print out the witness value instead, which is more useful for debugging purpose.
For example:
```rust
fn mimc7_hash(values: [Field; LEN], key: Field) -> Field {
// Initialize with the key.
let mut res = key;
// Iterate over each value in the input array.
for value in values {
// Update the result with the MIMC hash of the value and the current result.
res = res + (value + mimc7_cipher(value, res));
log(res);
}
// Return the final accumulated result.
return res;
}
```
It will print out:
```
span:9904, val: -9648106414739122877149794902860786266420046965962985658208312984077979135149
span:9904, val: 5233261170300319370386085858846328736737478911451874673953613863492170 …
```

supporting debug var value

---

src/backends/kimchi/mod.rs
src/backends/mod.rs
src/backends/r1cs/arkworks.rs
src/backends/r1cs/mod.rs
src/circuit_writer/mod.rs
src/compiler.rs
src/tests/examples.rs
src/tests/stdlib/mod.rs
src/utils/mod.rs
src/witness.rs

this adds some problem when we will split the `run` into `compile` and `run` commands. Right now we have access to the sources BECAUSE we produce the witness in the same command that compiles the circuit.
If we compile the circuit in one command (producing a compiled circuit artifact), then try to generate a witness in another command we might not have access to `Sources` anymore.
The solution will probably be to precompute what we need from sources in advance and add that to the `debug_info`

better log output

---

examples/fixture/asm/kimchi/unused_variables.asm
examples/fixture/asm/r1cs/unused_variables.asm
examples/unused_variables.no
src/backends/kimchi/mod.rs
src/backends/kimchi/prover.rs
src/backends/mod.rs
src/backends/r1cs/arkworks.rs
src/backends/r1cs/mod.rs
src/circuit_writer/mod.rs
src/cli/cmd_build_and_check.rs
src/cli/cmd_prove_and_verify.rs
src/compiler.rs
src/negative_tests.rs
src/tests/examples.rs
src/tests/modules.rs
src/tests/stdlib/mod.rs

This option allows variables that are not constrained.
Right now, it's a bit ugly how this parameter has to be passed. I will explain the workflow below, but I guess in the future, we can have a struct to capture parameters and pass them around so we can have access to user-defined configs. 
We need to add some ifs for this particular feature when we validate that variables have been used. This is happening in the `finalize_circuit` function inside circuit_writer instead of in the type checking and semantic checks. To pass the parameter from the UI based on which we are going to return an error or not, we do the following:
1. Add the option to `cli/cmd_build_and_check.rs` and `cli/cmd_prove_and_verify.rs`
2. Add bool parameter (`disable_safety_check`) in `compiler.rs::compile` function
3. …

Add --disable-safety-check option

---

src/error.rs
src/parser/mod.rs
src/parser/types.rs

This PR addresses this issue: https://github.com/zksecurity/noname/issues/236

Improve error when a keyword is used as identifier

---

src/circuit_writer/mod.rs
src/circuit_writer/writer.rs
src/imports.rs
src/mast/mod.rs
src/negative_tests.rs
src/stdlib/bits.rs
src/stdlib/builtins.rs
src/stdlib/crypto.rs
src/stdlib/int.rs
src/stdlib/mod.rs
src/type_checker/checker.rs
src/type_checker/mod.rs
src/witness.rs

Attempts to resolve #228.
Here is my approach:
As suggested in #228 I first introduced a new flag for the `FnKind::Builtin` called `ignore_arg_types`:
https://github.com/bufferhe4d/noname/blob/b243dce51ddbb96babf627fd3c1a8b5266d261ab/src/imports.rs#L78
Propagated this to all the occurrences of this. Then implemented the actual skip in the type checker.

Add boolean flag to skip argument type checking of builtin functions.

---

src/stdlib/native/int/lib.no

fix potential uint overflow

---

Cargo.lock
Cargo.toml
src/backends/kimchi/prover.rs
src/backends/r1cs/mod.rs
src/backends/r1cs/snarkjs.rs
src/inputs.rs
src/serialization.rs
src/stdlib/bits.rs

Kimchi was upgraded to a newer version that uses Arkworks 0.4, and Arkworks dependencies were upgraded to match those used by Kimchi (either 0.4.0 or 0.4.2 depending).

Upgrade to arkworks 0.4.0/2

---

src/stdlib/bits.rs
src/stdlib/builtins.rs
src/stdlib/crypto.rs
src/stdlib/int.rs

Addresses this issue https://github.com/zksecurity/noname/issues/227.
Already merged with https://github.com/zksecurity/noname/pull/238.

Add Builtin trait and refactor all builtin functions to use it

---

examples/log.no
examples/tuple.no
examples/types_array.no
src/backends/mod.rs
src/circuit_writer/ir.rs
src/circuit_writer/writer.rs
src/error.rs
src/inputs.rs
src/mast/mod.rs
src/name_resolution/context.rs
src/name_resolution/expr.rs
src/parser/expr.rs
src/parser/types.rs
src/stdlib/builtins.rs
src/type_checker/checker.rs
src/type_checker/mod.rs
src/utils/mod.rs

closes #255 
the example file can be found here [tuple.no](https://github.com/0xnullifier/noname/blob/feat-tuple/examples/tuple.no) this works and runs the output is:
I have not implemented destructuring as that is potentially another pr.
The code is pretty much identical to array type as tuple is just a multi-type array
and also as @mimoo suggested that we should keep the tuple access similar to array access. I have just changes the code for `ExprKind::ArrayAccess` to `ExprKind::ArrayOrTupleAccess` as they are identical at lexer level and dealt with this at type checker and writer.
it also refactors the array logging and combines it to array or tuple logging

Adds tuple type 

---

src/negative_tests.rs
src/type_checker/checker.rs
src/type_checker/fn_env.rs

When mutable constant variable is modified in a for loop, it should be marked as a non constant field. 
Otherwise the MAST phase will try to constant fold that variable into wrong constant value, because we don't support unrolling in for loop.

fix: invalid folded mutable constant value

---

src/mast/mod.rs

found this bug while implementing smt in stdlib [here](https://github.com/zksecurity/noname/pull/249#issuecomment-2604436495)

bug-fix: correct type matching in if-else expression

---

.github/workflows/gh-pages.yml
.github/workflows/rust.yml

Node 20 compatibility: switch all jobs to actions/checkout@v4. Pure maintenance, behavior unchanged.

ci: bump actions/checkout to v4

---

.github/workflows/gh-pages.yml

This PR updates the `peaceiris/actions-gh-pages` GitHub Action from version `v3` to the latest stable version `v4`.  
The update ensures compatibility with the latest GitHub Actions runtime and includes performance improvements and bug fixes introduced in v4.
Reference: https://github.com/peaceiris/actions-gh-pages/releases

update action: peaceiris/actions-gh-pages from v3 to v4

---

src/parser/expr.rs

Spotted and fixed a few wording hiccups:
`if if` - fix duplicate

polishing docs: error fixes for clarity

---

book/src/cellvar.md

https://mimoo.github.io/noname/rustdoc/var/struct.CellVar.html - is broken and there is no any information about this across google

docs: remove broken link

---

book/src/modules.md
book/src/rfc/rfc-0-generic-parameters.md

cyles -> cycles
struture -> structure
relyin -> relying
addtional -> additional

doc: fix some grammatical issue across docs
